### ISSUE TITLE
UAT | Armenia vs EU only shows 2 families in the overview dynamic benchmarking

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#222]
This may be a more general issue with dynamic benchmarking. 

Armenia vs EU only shows HRM and Climate. This is too low. Let us please revise what is happening.

**Comment by kannanv93** [comment]
@galileukim Looks like there is some data issue with Armenia. All average except the two shown above are all NA.


<img width="742" alt="image" src="https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/6178e563-8dcf-4b99-9a8b-70db7dbc63cd">

**Comment by galileukim** [comment]
@erwbg this is helpful, thank you. please note that all sven institutional family averages mentioned above are included in our dynamic benchmarking. it is just the case that for some countries, some of the institutional family averages cannot be computed due to missingness of indicators. this does not mean we do not have an overview tab in the dynamic benchmarking. for example, even for Armenia, we still have averages computed for the (1) Climate Change and (2) Public HRM institutional families. therefore, there should be an overview tab for it, with only the institutional family averages for (1) and (2).

**Comment by kannanv93** [comment]
@erwbg  : Please check uat_2 and close this issue

**Comment by kannanv93** [comment]
@erwbg  : Any problem with this ? Can we close this if tested.
