### ISSUE TITLE
UAT | Issues with "original indicators" data download 

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#224]
- [x] "Original indicators" should not include family averages --but they're included now.
- [x] “Original indicators” should also include "not benchmarked" indicators --but they're not included now.

**Comment by galileukim** [comment]
Thank you for raising this.

1.	Regarding the family averages, currently these are included in the pipeline so that Kannan can provide dynamic benchmarks using the original indicators. If we are to drop them from download, we should introduce a filter in the dashboard at the download stage – not pipeline – perhaps with a `select(-ends_with(“_avg”))` command.
2.	The non-benchmarked and all “other” indicators are included in the pipeline stage and copied to the dashboard as is. I checked our CLIAR_UAT branch and all variables are presented in the `compiled_indicators.rds` file. @kannanv93 , are we introducing some form of filter at the download stage?
