### ISSUE TITLE
UAT 2 | Static Benchmarking in the Dashboard is missing Family Avgs in the within family graphs

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#229]
if global CTF is not computed for a family (e.g., static, service delivery), the "FAMILY AVG" is not displayed in the family-by-family graph.

Potential solution: estimate all family avgs in the ETL, but put them to "missing" --and the reactively estimate those values in the dashboard

**Comment by kannanv93** [comment]
@galileukim 

Currently Service Delivery Average is not being computed because of the following code in 04_ctf.

ctf_static_family <- ctf |> 
  compute_family_average(
    vars = **vars_static_family_ctf**,
    db_variables = db_variables
  )

vars_static_family_ctf <- db_variables |>
  filter(
    **benchmark_static_family_aggregate_download == "Yes"**
  ) |>
  pull(variable)

I think we should compute data for Service Delivery too here and directly exclude this family from Overview tab.

**Comment by galileukim** [comment]
@kannanv93 and @erwbg, I was waiting on implementing this task because I wanted us to have clarity if introducing this family averages cascade in our dashboard. In particular, I'm worried that for some tabs (e.g., scatterplot), users will select the indicator for Service Delivery Family Average and have a strange error they can't understand.

**Comment by kannanv93** [comment]
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/16816700/25677b21-3a9b-4a07-a805-36f57be0956c)

@erwbg : Please test and close the issue
