### ISSUE TITLE
CLIAR_UAT | Custom groups not working

### ISSUE THREAD

**Issue by erwbg** [worldbank/institutional-assessment-dashboard#262]
@kannanv93, would you please check what's going on with the custom groups? We can select but then they're not being applied to the benchmarking

A second point: now the interface allows you to select up to 5 custom groups. We should limit that to 3.

**Comment by kannanv93** [comment]
@erwbg : please check new version. Seems to be working fine. Please add show comparison countries and share screenshot if its not working

Fixed Point 2.

**Comment by erwbg** [comment]
Not working for me. Image here
![image](https://github.com/worldbank/institutional-assessment-dashboard/assets/127211275/9a658abf-f603-4519-96d3-508df3021275)

**Comment by kannanv93** [comment]
@erwbg Issue has been fixed. The reason for this issue was that we have a button benchmark_median in our previous version. We had hid that button but we had that auto-selected when a custom group was created. After UI update, the button was removed leading to null resulting in not showing the custom group. 

We can discuss this in our next meeting and decide how to act.
